name: Deploy WP Theme to Production & Development

on:
  push:
    branches:
      - main        # Production deployment
      - dev         # Development deployment
  workflow_dispatch:  # Allow manual triggers
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production
      force_deploy:
        description: 'Force deployment (skip safety checks)'
        required: false
        type: boolean
        default: false

jobs:
  deploy-theme:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    
    env:
      # Common settings
      THEME_SUBDIR: wp-content/themes/theme-location
      BACKUP_DIR: /tmp/wordpress-theme-backup
      MAX_RETRIES: 3
      RSYNC_TIMEOUT: 300
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Determine deployment environment
        id: env-setup
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]] || [[ "${{ inputs.environment }}" == "production" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_OUTPUT
            echo "SSH_HOST=${{ secrets.PRODUCTION_SSH_HOST }}" >> $GITHUB_OUTPUT
            echo "SSH_USER=${{ secrets.PRODUCTION_SSH_USER }}" >> $GITHUB_OUTPUT
            echo "SSH_PORT=${{ secrets.PRODUCTION_SSH_PORT || '22' }}" >> $GITHUB_OUTPUT
            echo "DEPLOY_PATH=${{ secrets.PRODUCTION_SSH_PATH }}" >> $GITHUB_OUTPUT
            echo "SITE_URL=https://abc.com" >> $GITHUB_OUTPUT
            echo "FILE_OWNER=${{ secrets.PRODUCTION_SSH_OWNER || 'www:www' }}" >> $GITHUB_OUTPUT
            echo "SSH_KEY_SECRET=PRODUCTION_SSH_KEY" >> $GITHUB_OUTPUT
            FULL_DEPLOY_PATH="${{ secrets.PRODUCTION_SSH_PATH }}/${THEME_SUBDIR}"
          else
            echo "ENVIRONMENT=development" >> $GITHUB_OUTPUT
            echo "SSH_HOST=${{ secrets.DEVELOPMENT_SSH_HOST }}" >> $GITHUB_OUTPUT
            echo "SSH_USER=${{ secrets.DEVELOPMENT_SSH_USER }}" >> $GITHUB_OUTPUT
            echo "SSH_PORT=${{ secrets.DEVELOPMENT_SSH_PORT || '22' }}" >> $GITHUB_OUTPUT
            echo "DEPLOY_PATH=${{ secrets.DEVELOPMENT_PATH }}" >> $GITHUB_OUTPUT
            echo "SITE_URL=https://abc.mode-developer.com" >> $GITHUB_OUTPUT
            echo "FILE_OWNER=${{ secrets.DEVELOPMENT_SSH_OWNER || 'team:team' }}" >> $GITHUB_OUTPUT
            echo "SSH_KEY_SECRET=DEVELOPMENT_SSH_KEY" >> $GITHUB_OUTPUT
            FULL_DEPLOY_PATH="${{ secrets.DEVELOPMENT_PATH }}/${THEME_SUBDIR}"
          fi
          
          echo "FULL_DEPLOY_PATH=${FULL_DEPLOY_PATH}" >> $GITHUB_OUTPUT

      - name: Validate deployment prerequisites
        run: |
          echo "Validating deployment configuration..."
          
          # Validate theme directory exists in repository
          if [[ ! -d "./${THEME_SUBDIR}" ]]; then
            echo "Theme directory not found in repository: ./${THEME_SUBDIR}"
            exit 1
          fi
          
          # Check that we have the required environment variables
          if [[ -z "${{ steps.env-setup.outputs.SSH_HOST }}" ]]; then
            echo "SSH_HOST not configured for ${{ steps.env-setup.outputs.ENVIRONMENT }} environment"
            exit 1
          fi
          
          if [[ -z "${{ steps.env-setup.outputs.SSH_USER }}" ]]; then
            echo "SSH_USER not configured for ${{ steps.env-setup.outputs.ENVIRONMENT }} environment"
            exit 1
          fi
          
          if [[ -z "${{ steps.env-setup.outputs.DEPLOY_PATH }}" ]]; then
            echo "DEPLOY_PATH not configured for ${{ steps.env-setup.outputs.ENVIRONMENT }} environment"
            exit 1
          fi
          
          echo "All prerequisites validated"
          echo "Environment: ${{ steps.env-setup.outputs.ENVIRONMENT }}"
          echo "Target URL: ${{ steps.env-setup.outputs.SITE_URL }}"
          echo "Deploy Path: ${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }}"

      - name: Set up SSH key and known hosts
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ steps.env-setup.outputs.SSH_KEY_SECRET == 'PRODUCTION_SSH_KEY' && secrets.PRODUCTION_SSH_KEY || secrets.DEVELOPMENT_SSH_KEY }}

      - name: Add server to known hosts
        run: |
          echo "Adding server to known hosts..."
          ssh-keyscan -p ${{ steps.env-setup.outputs.SSH_PORT }} \
            ${{ steps.env-setup.outputs.SSH_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Test SSH connection
        run: |
          echo "Testing SSH connection..."
          ssh -o ConnectTimeout=10 \
              -p ${{ steps.env-setup.outputs.SSH_PORT }} \
              ${{ steps.env-setup.outputs.SSH_USER }}@${{ steps.env-setup.outputs.SSH_HOST }} \
              "echo 'SSH connection successful' && whoami && pwd"

      - name: Verify remote directory structure
        run: |
          echo "Verifying remote directory structure..."
          ssh -p ${{ steps.env-setup.outputs.SSH_PORT }} \
              ${{ steps.env-setup.outputs.SSH_USER }}@${{ steps.env-setup.outputs.SSH_HOST }} \
              "mkdir -p '${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }}' && \
               ls -la '$(dirname ${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }})' && \
               echo 'Target directory: ${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }}'"

      - name: Create backup of current theme
        if: steps.env-setup.outputs.ENVIRONMENT == 'production' || inputs.force_deploy != true
        run: |
          echo "Creating backup of current theme..."
          BACKUP_NAME="theme-backup-$(date +%Y%m%d-%H%M%S)"
          
          ssh -p ${{ steps.env-setup.outputs.SSH_PORT }} \
              ${{ steps.env-setup.outputs.SSH_USER }}@${{ steps.env-setup.outputs.SSH_HOST }} \
              "if [[ -d '${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }}' ]]; then
                 mkdir -p '${BACKUP_DIR}' && \
                 cp -r '${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }}' '${BACKUP_DIR}/${BACKUP_NAME}' && \
                 echo 'Backup created: ${BACKUP_DIR}/${BACKUP_NAME}' && \
                 ls -la '${BACKUP_DIR}/${BACKUP_NAME}' | head -10
               else
                 echo 'No existing theme to backup'
               fi"
          
          echo "BACKUP_NAME=${BACKUP_NAME}" >> $GITHUB_ENV

      - name: Deploy theme via rsync
        id: deploy
        run: |
          echo "Starting deployment to ${{ steps.env-setup.outputs.ENVIRONMENT }}..."
          
          # Rsync with comprehensive options
          rsync_cmd="rsync \
            --archive \
            --verbose \
            --compress \
            --delete \
            --delete-excluded \
            --human-readable \
            --progress \
            --timeout=${RSYNC_TIMEOUT} \
            --exclude='.git*' \
            --exclude='node_modules/' \
            --exclude='*.log' \
            --exclude='.env*' \
            --exclude='*.tmp' \
            --exclude='.DS_Store' \
            -e 'ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -p ${{ steps.env-setup.outputs.SSH_PORT }}' \
            ./${THEME_SUBDIR}/ \
            ${{ steps.env-setup.outputs.SSH_USER }}@${{ steps.env-setup.outputs.SSH_HOST }}:'${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }}/'"
          
          # Execute with retry logic
          for attempt in $(seq 1 $MAX_RETRIES); do
            echo "Deployment attempt $attempt of $MAX_RETRIES..."
            
            if eval "$rsync_cmd"; then
              echo "Deployment successful on attempt $attempt"
              echo "deployment_success=true" >> $GITHUB_OUTPUT
              break
            else
              echo "Deployment attempt $attempt failed"
              if [[ $attempt -eq $MAX_RETRIES ]]; then
                echo "All deployment attempts failed"
                echo "deployment_success=false" >> $GITHUB_OUTPUT
                exit 1
              fi
              echo "Waiting 10 seconds before retry..."
              sleep 10
            fi
          done

      - name: Set file permissions and ownership
        if: steps.deploy.outputs.deployment_success == 'true'
        run: |
          echo "Setting proper file permissions and ownership..."
          
          ssh -p ${{ steps.env-setup.outputs.SSH_PORT }} \
              ${{ steps.env-setup.outputs.SSH_USER }}@${{ steps.env-setup.outputs.SSH_HOST }} \
              "cd '${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }}' && \
               find . -type f -exec chmod 644 {} \; && \
               find . -type d -exec chmod 755 {} \; && \
               echo 'File permissions set (644 for files, 755 for directories)'"
          
          # Set ownership (only if user has permission - using sudo is optional)
          ssh -p ${{ steps.env-setup.outputs.SSH_PORT }} \
              ${{ steps.env-setup.outputs.SSH_USER }}@${{ steps.env-setup.outputs.SSH_HOST }} \
              "cd '${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }}' && \
               (sudo chown -R '${{ steps.env-setup.outputs.FILE_OWNER }}' . && \
                echo 'Ownership set to ${{ steps.env-setup.outputs.FILE_OWNER }}') || \
               echo 'Could not change ownership (insufficient permissions)'"

      - name: Verify deployment
        if: steps.deploy.outputs.deployment_success == 'true'
        run: |
          echo "Verifying deployment..."
          
          ssh -p ${{ steps.env-setup.outputs.SSH_PORT }} \
              ${{ steps.env-setup.outputs.SSH_USER }}@${{ steps.env-setup.outputs.SSH_HOST }} \
              "cd '${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }}' && \
               echo 'Deployed files:' && \
               find . -maxdepth 2 -type f | head -20 && \
               echo '' && \
               echo 'Directory size:' && \
               du -sh . && \
               echo '' && \
               echo 'Latest files:' && \
               find . -type f -printf '%T@ %p\n' | sort -n | tail -5 | cut -d' ' -f2-"

      - name: WordPress cache cleanup (optional)
        if: steps.deploy.outputs.deployment_success == 'true'
        continue-on-error: true
        run: |
          echo "Attempting to clear WordPress cache..."
          
          ssh -p ${{ steps.env-setup.outputs.SSH_PORT }} \
              ${{ steps.env-setup.outputs.SSH_USER }}@${{ steps.env-setup.outputs.SSH_HOST }} \
              "cd '${{ steps.env-setup.outputs.DEPLOY_PATH }}' && \
               if [[ -f 'wp-config.php' ]]; then
                 # Clear common cache locations
                 rm -rf wp-content/cache/* 2>/dev/null || true
                 rm -rf wp-content/uploads/cache/* 2>/dev/null || true
                 echo 'Basic cache cleanup completed'
               else
                 echo 'wp-config.php not found, skipping cache cleanup'
               fi"

      # Rollback on failure
      - name: Rollback on deployment failure
        if: failure() && env.BACKUP_NAME != ''
        run: |
          echo "Rolling back to previous version..."
          
          ssh -p ${{ steps.env-setup.outputs.SSH_PORT }} \
              ${{ steps.env-setup.outputs.SSH_USER }}@${{ steps.env-setup.outputs.SSH_HOST }} \
              "if [[ -d '${BACKUP_DIR}/${BACKUP_NAME}' ]]; then
                 rm -rf '${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }}' && \
                 mv '${BACKUP_DIR}/${BACKUP_NAME}' '${{ steps.env-setup.outputs.FULL_DEPLOY_PATH }}' && \
                 echo 'Rollback completed successfully'
               else
                 echo 'Backup not found, rollback failed'
               fi"

      - name: Deployment Summary
        if: always()
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Attribute | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| **Environment** | ${{ steps.env-setup.outputs.ENVIRONMENT }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Target URL** | ${{ steps.env-setup.outputs.SITE_URL }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Branch** | ${{ github.ref_name }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Commit** | ${{ github.sha }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Author** | ${{ github.actor }} |" >> $GITHUB_STEP_SUMMARY
          echo "| **Status** | ${{ job.status }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ job.status }}" == "success" ]]; then
            echo "**Deployment completed successfully!**" >> $GITHUB_STEP_SUMMARY
          else
            echo "**Deployment failed. Check logs for details.**" >> $GITHUB_STEP_SUMMARY
          fi
